Updating the MAINTAINERS.md file
opensearch-project/dashboards-notifications pull request #42
Opened 2023-05-09 19:38 UTC by bbarani

### Description
Updated the MAINTAINERS.md file 

### Issues Resolved
Closes #37 

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-05-09 19:41 UTC, bbarani commented
@SuZhou-Joe Please merge this PR when you get time. I have fixed permissions in this repo.

2023-05-09 23:21 UTC, xluo-aws commented on MAINTAINERS.md
> +| Yuye Zhu              | [SuZhou-Joe](https://github.com/yuye-aws)   | Amazon      |
Github ID should be yuye-aws, not SuZhou-Joe

2023-05-09 23:22 UTC, xluo-aws commented on MAINTAINERS.md
> +| zhichao               | [SuZhou-Joe](https://github.com/zhichao-aws)   | Amazon      |
Name is Zhichao Geng, Github id should be zhichao-aws, not SuZhou-Joe

2023-05-10 06:39 UTC, SuZhou-Joe requested changes

2023-05-10 06:39 UTC, SuZhou-Joe commented on MAINTAINERS.md
> +| Yuye Zhu              | [SuZhou-Joe](https://github.com/yuye-aws)   | Amazon      |
```suggestion
| Yuye Zhu              | [yuye-aws](https://github.com/yuye-aws)   | Amazon      |
```

2023-05-10 06:39 UTC, SuZhou-Joe commented on MAINTAINERS.md
> +| zhichao               | [SuZhou-Joe](https://github.com/zhichao-aws)   | Amazon      |
```suggestion
| zhichao               | [zhichao-aws](https://github.com/zhichao-aws)   | Amazon      |
```

2023-05-10 07:56 UTC, SuZhou-Joe approved these changes

2023-05-10 07:58 UTC, xluo-aws approved these changes

2023-05-10 07:59 UTC, merged